name: azure-test
description: Data to get data from the Odoo Test VM
initialize:
  plugins:
    azure-importer:
      method: AzureImporter
      path: "@grnsft/if-unofficial-plugins"
    cloud-metadata:
      method: CloudMetadata
      path: "@grnsft/if-plugins"
    teads-curve:
      method: TeadsCurve
      path: "@grnsft/if-unofficial-plugins"
    string-to-number-plugin:
      path: "string-to-number-plugin"
      method: StringToNumberPlugin
tree:
  children:
    child:
      pipeline:
        - azure-importer
        - cloud-metadata
        - string-to-number-plugin
        - teads-curve
      config:
        azure-importer:
          azure-observation-window: 5 min
          azure-observation-aggregation: "average"
          azure-subscription-id: eb31efe5-ba49-481f-b1e6-add66b5fbe80
          azure-resource-group: cws-test-chn1-odoo-rg-01
          azure-vm-name: chn1t-odoo-vm
        string-to-number-plugin:
          from-parameter: cpu/utilization
      inputs:
        - timestamp: "2024-05-07T17:00:00.000Z"
          duration: 3600 # 1468800
